blend_path: ${oc.env:PWD}/src/nemotron/recipes/nano3/stage0_pretrain/config/data_prep/data_blend_raw_small.json
output_dir: ${oc.env:PWD}/../output/stage0_pretrain_tiny
num_shards: 4
valid_shards: 1
test_shards: 1
tokenizer_model: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-Base-BF16
add_bos: false
add_eos: true
text_field: text
min_doc_chars: null
max_doc_tokens: null
sample: 1000
num_actors: null
force: false
